### ISSUE TITLE
openSource item - ltr on the hebrew site

### ISSUE THREAD

**Issue by danasegal1** [DataCyberDevelopment/ui-db---frontEnd#51]
ltr on both english and hebrew sites

<img width="977" alt="Screen Shot 2021-11-25 at 13 34 52" src="https://user-images.githubusercontent.com/95017644/143435541-9eb36c36-6642-4cb7-8b38-7c9329b465ef.png">

**Comment by danasegal1** [comment]
this page from now, its only with english version

**Comment by orchoban** [comment]
@touhidbd 
I tried to put `ltr` className for all this part but it not work.
For now I want it with English version only until we have translated everything.
I do not want to change the site language, I just want to change the container of this page without head and footer.
You did not separate the scss well into the RTL and LTR files so it did not work.

I want the whole site to be able to have a `.ltr` or `.rtl`  and a certain container to be with opposite direction className.
For this you need a general style, a RTL style and a LTR style.
If you have another idea, Let me know.

![image](https://user-images.githubusercontent.com/33927385/143542334-8d9072a1-f1c8-4c3d-a8b9-b4b3b23b8702.png)

![image](https://user-images.githubusercontent.com/33927385/143542379-35346894-1166-4c6b-aac5-aad64258c933.png)

**Comment by touhidbd** [comment]
@orchoban Actually, we don't need to write extra CSS for `LTR` because this is the main design. So, I make condition CSS code when the `rtl` class. This trick saves us a lot of code writing. 

If you don't change the RTL just remove `rtl` class. If you have any questions please let me know.

![image](https://user-images.githubusercontent.com/8915879/143590105-d58550d4-f357-45d9-bf77-6fa5083cb930.png)

**Comment by orchoban** [comment]
I understand it.

not solved yet.

http://test.ui-db.com/he/open-source/react.cordova-navigation_controller
